tokenForHarmonist17 <- Sys.getenv("tokenForHarmonist17")
tokenForHarmonist4 <- Sys.getenv("tokenForHarmonist4")
tokenForHarmonist17A <- Sys.getenv("tokenForHarmonist17A")
tokenForHarmonist9 <- Sys.getenv("tokenForHarmonist9")
tokenForHarmonist18 <- Sys.getenv("tokenForHarmonist18")
tokenForHarmonist3 <- Sys.getenv("tokenForHarmonist3")
tokenForHarmonist5 <- Sys.getenv("tokenForHarmonist5")
tokenForAfricaAgg <- Sys.getenv("tokenForAfricaAgg")
tokenForHarmonist11 <- Sys.getenv("tokenForHarmonist11")
#tokenForAfricaAgg <- Sys.getenv("tokenForAfricaAgg")
tokenForHarmonist0C <- Sys.getenv("tokenForHarmonist0C")
tokenForHarmonistChangelog <- Sys.getenv("tokenForHarmonistChangelog")
encryptionKey <- Sys.getenv("encryptionKey") # for token decryption
encryptionIV <- Sys.getenv("encryptionIV")